---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: development
spec:
  selector:
    app: ropc-service
  ports:
    - port: 8082
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: ropc-db
  namespace: development
spec:
  selector:
    app: ropc-db
  ports:
    - port: 5432
  type: ClusterIP